#!/usr/bin/env bash

# From https://github.com/ksoichiro/dockerfiles/blob/master/android-emulator/start-emulator

while getopts "a:b:" arg
do
    case $arg in
        a) # do after emulator start
            AFTER_CMD=$OPTARG
            ;;
        b) # do before emulator start
            BEFORE_CMD=$OPTARG
            ;;
    esac
done

echo "Starting emulator..."
emulator64-arm -avd test -no-skin -no-audio -no-window -gpu off &
$BEFORE_CMD
android-wait-for-emulator
$AFTER_CMD

